import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSwrGql } from "@packages/swr-gql/useSwrGql";
import { ContinentsDocument, ContinentsQuery } from "../src/codegen";
import { gqlRequest } from "@packages/swr-gql/gqlRequest";

const Home: NextPage<ContinentsQuery> = (props) => {
  const { data } = useSwrGql(
    ContinentsDocument,
    {},
    { url: "https://countries.trevorblades.com/", fallbackData: props }
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        {data &&
          data.continents.map((continent) => (
            <div key={continent.code}>{continent.name}</div>
          ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const data = await gqlRequest(
    ContinentsDocument,
    {},
    "https://countries.trevorblades.com/"
  );
  return {
    props: data,
  };
};

export default Home;
